### ISSUE TITLE
producers make amq.gen-XXXXX queue.... 

### ISSUE THREAD

**Issue by pinouf** [fiunchinho/rabbitmq-service-provider#3]
hello,

i have a big problem...
i Have a producer define with:

                'rabbit.producers'   => [
                    'content_manager' => [
                        'connection'       => 'default',
                        'exchange_options' => ['name' => 'mirror.Service', 'type' => 'topic', 'durable' => true]
                    ],
                ],
i have severals consumers:

                'rabbit.consumers'   => [
                    'worker_manager_upload'                    => [
                        'connection'       => 'default',
                        'exchange_options' => ['name' => 'mirror.Service', 'type' => 'topic'],
                        'queue_options'    => [
                            'name'         => 'mirror.converterUploadQueue',
                            'routing_keys' => ['workermanager.content.upload']
                        ],
                        'callback'         => 'kadrige.workers.upload.consumer'
                    ],
                    'worker_manager_zip'                       => [
                        'connection'       => 'default',
                        'exchange_options' => ['name' => 'mirror.Service', 'type' => 'topic'],
                        'queue_options'    => [
                            'name'         => 'mirror.converterZipQueue',
                            'routing_keys' => ['workermanager.content.zip']
                        ],
                        'callback'         => 'kadrige.workers.zip.consumer'
                    ],

the projet is duplicate in severals servers.
each time a server produce a message by exemple in workermanager.content.upload routing key, i have a queue which is generate amq.gen-XXxXXX with no consumer connected...
The problem is that now i have 300 queue amq.gen-Xxxxxx 

i would like that the producer send the message directly in the good queue... , in my case the queue name is mirror.converterUploadQueue ...

thank you...

**Comment by fiunchinho** [comment]
If you want to send messages directly to a particular queue, don't use "topic". Please, read the RabbitMQ manual http://www.rabbitmq.com/tutorials/tutorial-four-python.html

**Comment by AlexStansfield** [comment]
I'm having the same issue and I don't really understand your solution.

We have exchanges setup as topic exchanges. They already have queues bound to them where messages should be routed depending on the routing key.

I want to just send a message to the exchange and have rabbit decide on the routing I don't need any extra queues created.

If I remove topic from the exchange_options then it throw an error. So what should I do to stop these random queues being created?

**Comment by AlexStansfield** [comment]
We also have the same symfony bundle setup in a symfony project. It's setup the same way, no consumers just a producer that sends to the topic exchange. This code doesn't create extra queues.

**Comment by AlexStansfield** [comment]
In the symfony bundle extension is this code where it setups up producers

```
//this producer doesn't define a queue
if (!isset($producer['queue_options'])) {
    $producer['queue_options']['name'] = null;
}
$definition->addMethodCall('setQueueOptions', array($producer['queue_options']));
```

I copied it into the Silex Service Provider as 

```
if (!isset($options['queue_options'])) {
    $options['queue_options']['name'] = null;
}
$producer->setQueueOptions($options['queue_options']);
```

No more random queues created.

**Comment by pinouf** [comment]
@AlexStansfield  , is that your solution work?

i gave up because i dont find a solution .. i created a rules who delete extra queue in rabbitmq admin to resolve my problem.

**Comment by AlexStansfield** [comment]
Yep, there was some code missing from the Service Provider that stopped the producer from creating a random queue if you didn't configure any queues.

I've tested it and it works. Looks like it's been merged already.
