### ISSUE TITLE
Replace abandoned oldsound/rabbitmq-bundle

### ISSUE THREAD

**Issue by mattattui** [fiunchinho/rabbitmq-service-provider#9]
Fortunately `php-amqplib/rabbitmq-bundle` is a drop-in replacement. It just has new maintainers.

**Comment by AntonStoeckl** [comment]
I changed it in my fork. Don't know exactly when I'll be able to supply a beta version. Hopefully soon.
https://github.com/e-Sixt/rabbitmq-service-provider

**Comment by AlexStansfield** [comment]
@AntonStoeckl great work. any chance you'll be putting it on packagist?

**Comment by AntonStoeckl** [comment]
@AlexStansfield 
It's already on Packagist for a while: https://packagist.org/packages/e-sixt/rabbitmq-service-provider
I'll build a 1.0.0 release soon, probably today. Currently it's a RC1 and I can't test everything (e.g. RPC, multi consumer). I kept fiunchinho's namespace so it works out of the box.

**Comment by AntonStoeckl** [comment]
@AlexStansfield 

I just did a 1.1.0 release!
